// This file is generated by npm run import:cards
export const importedNoteSections = [
  {
    "id": "2026-2026-03-08-1",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-08",
    "title": "2026",
    "body": "- You can parry.\n- Ma'am. Back of the line.\n- I know there's like items all around, so I got to not back myself into a corner. Whoopsie.\n- Okay. Okay, step one, don't back yourself into a corner. Step two, go into the houses and try and get the loot. Step three, use your make sure you kick them.\n- Excuse me. Excuse me. I'm going to die. Okay. Is this Is this real?\n- Let me look at this freaking map.",
    "excerpt": "- You can parry. - Ma'am. Back of the line. - I know there's like items all around, so I got to not back myself into a corner. Whoopsie. - O",
    "wordCount": 84
  },
  {
    "id": "2026-2026-03-09-2",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-09",
    "title": "2026",
    "body": "- There's just stuff in here. (truncated)\n- Don't go in.\n- And then we sneak in her house and we take all our chickens.\n- The one house I didn't go in.\n- I'm going to lose my mind. (truncated)\n- You gotta be kidding me.\n- Look, we even skipped his grand entry.\n- You got to be kidding me.\n- Wait, there it is.\n- The definition of insanity is doing the same thing. (truncated)\n- No, cuz I'm going to get stuck in them.\n- How long do I have to. (truncated)\n- probably get it.\n- You'd like that, wouldn't you?\n- You can't turn it back.\n- Oh god.\n- Cruelty.\n- Shoot the bell to power.\n- Does that scare them?",
    "excerpt": "- There's just stuff in here. (truncated) - Don't go in. - And then we sneak in her house and we take all our chickens. - The one house I di",
    "wordCount": 128
  },
  {
    "id": "2026-2026-03-10-3",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-10",
    "title": "2026",
    "body": "- mean? This is a strat when you are bad at the game.\n- Oh, it's getting a little dicey. It's getting a little hairy in here.\n- Are you frustrated?\n- Well, that was spooky.\n- can loot everything because Resident Evil likes to make me go crazy.\n- Fortnite's going to be for old people. So count your days.\n- Anybody who just scoffed, if you blew a significant amount of air out of your nose when I said bingo, that sounds",
    "excerpt": "- mean? This is a strat when you are bad at the game. - Oh, it's getting a little dicey. It's getting a little hairy in here. - Are you frus",
    "wordCount": 84
  },
  {
    "id": "2026-2026-03-12-4",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-12",
    "title": "2026",
    "body": "- nose when I said bingo, that sounds fun. Count your days.\n- Okay. I'm into Oh, well, we'll go in here.\n- That's going to be annoying.\n- A box. A ruby.\n- I think that's kind of funny, too, cuz I'm pretty sure they're like rather strict about how Miku appears, like what Miku is. Miku is a pop idol, you know?\n- This brown map is confusing. Everything looks the same.\n- We have so much of this now. I got to use this.\n- What if you're like significantly outnumbered by chickens",
    "excerpt": "- nose when I said bingo, that sounds fun. Count your days. - Okay. I'm into Oh, well, we'll go in here. - That's going to be annoying. - A ",
    "wordCount": 96
  },
  {
    "id": "2026-2026-03-14-5",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-14",
    "title": "2026",
    "body": "- Again? I'm going to lose my mind. I'm going to freak.\n- Coconut crabs. I like coconut crabs. They're so cute.\n- Wait, windmill. Where's the windmill?\n- Cuz the bell went bong. Okay, we go this way.\n- Goes the opposite way. Beef brisket. Yummy.\n- Had a lot of elbow macaroni stickers. Am I supposed to go up?\n- What do you get though? Is this worth my time?\n- It's worth it. Okay, I will trust you.",
    "excerpt": "- Again? I'm going to lose my mind. I'm going to freak. - Coconut crabs. I like coconut crabs. They're so cute. - Wait, windmill. Where's th",
    "wordCount": 81
  },
  {
    "id": "2026-2026-03-15-6",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-15",
    "title": "2026",
    "body": "- Wait, where was that? We have to like get.\n- Can I eat this?\n- The first mistake you made was it being a beep beep beep beep.\n- Somebody's talking to me I feel like I have to tell them I'm listening but I'm really not comprehending.\n- He's mutated.\n- That'll get her attention. And then we'll throw a dynamite.\n- What's that noise?\n- I don't think he's worth killing.",
    "excerpt": "- Wait, where was that? We have to like get. - Can I eat this? - The first mistake you made was it being a beep beep beep beep. - Somebody's",
    "wordCount": 74
  },
  {
    "id": "2026-2026-03-17-7",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-17",
    "title": "2026",
    "body": "- Slice of Slapperoni Pizza that restores Effective Health while also granting the Slap effect.\n- It's a man slay ride.\n- Think you can swallow me whole? Hun?\n- Please don't taunt the.\n- Bum bum bum. Is this a gambling game? I don't think so. It's Wheel of Fortune.\n- Audio is good. Shame as usual.\n- Ubisoft has monopoly. Has a monopoly or has monopoly?\n- See the answer and she'll help me out. Yes. Yes.\n- I have to get the crab hat. Oh boy, this is going to be rough.\n- What do you mean? Yikes. What's he talking about? Chill. Calm down.",
    "excerpt": "- Slice of Slapperoni Pizza that restores Effective Health while also granting the Slap effect. - It's a man slay ride. - Think you can swal",
    "wordCount": 108
  },
  {
    "id": "2026-2026-03-18-8",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-18",
    "title": "2026",
    "body": "- You are saying this because I have confidence in myself.\n- Okay, this one I will not look at what you are saying.\n- Anything like that. But in reality, he's actually sending a message to his friend.\n- When this guy starts waving his finger really.\n- Community loves her, but this time I regretted it.\n- Well, you can't be lying, sir. Not what I'm concerned about.\n- Oh, please demonstrate. All right.\n- Okay, I'll just go with the other one. Space it out. It helps.\n- Together in groups. Otherwise, they'll get lonely. Maybe it's the same thing.\n- Don't want to like force that on you just in case.",
    "excerpt": "- You are saying this because I have confidence in myself. - Okay, this one I will not look at what you are saying. - Anything like that. Bu",
    "wordCount": 115
  },
  {
    "id": "2026-2026-03-19-9",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-19",
    "title": "2026",
    "body": "- The non I'm just going to look it up.\n- You guys are going to mess me up.\n- Make him bald first with green skin.\n- Okay.\n- I cast baldness. Where is it?\n- What kind of mouth should we go with for green Sonic?\n- He's kind of got like a line that.\n- Got it. Try to be fast cuz I could be here for a while.\n- Yeah. Yeah. Yeah. Okay.\n- The ears are in the way. I'm thinking I'm going to delete the ears.\n- So, I'm just going to pretend they're not there.\n- I'm just going to look it up.",
    "excerpt": "- The non I'm just going to look it up. - You guys are going to mess me up. - Make him bald first with green skin. - Okay. - I cast baldness",
    "wordCount": 110
  },
  {
    "id": "2026-2026-03-21-10",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-21",
    "title": "2026",
    "body": "- Like this one should be good. Okay, so...\n- I'm just going to do half and then we're just going to multiply.\n- I can actually draw pretty well with mouse on MS Paint.\n- What? One more try.\n- It looks kind of like the same color, but I don't think it is. No, it needs to be like slightly lighter, I think.\n- At least the green Sonic like people aren't that passionate about, you know, and people are passionate about Sonic, don't get me wrong, but I don't... (truncated)\n- It changes depending on like what angle you're looking at it from.\n- Is there a way to zoom out? Like, hold on.",
    "excerpt": "- Like this one should be good. Okay, so... - I'm just going to do half and then we're just going to multiply. - I can actually draw pretty ",
    "wordCount": 117
  },
  {
    "id": "2026-2026-03-22-11",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-22",
    "title": "2026",
    "body": "- I'm not happy with this. We're getting there.\n- Should we go with these oblong? It's kind of like this but sideways.\n- Can I turn the eye sideways?\n- Hold on. I'm cooking.\n- They're probably going to go like here.\n- I think I'm going to go with this one. Can we go even further?\n- Wait, this looks pretty good. I think I'm going to go with this.\n- Wait, you know what? Let me change.\n- It doesn't really match with what I want.",
    "excerpt": "- I'm not happy with this. We're getting there. - Should we go with these oblong? It's kind of like this but sideways. - Can I turn the eye ",
    "wordCount": 89
  },
  {
    "id": "2026-2026-03-23-12",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-23",
    "title": "2026",
    "body": "- All right. And then the eyes.\n- Let me cook. Let me cook.\n- This is too much. This is too much detail.\n- It's a little uneven. I'm going to fix it.\n- Skill.\n- No, not that. Okay. Not yet. But they can eventually. Eventually. Wonder if I should make this like a little.\n- All done.\n- Like these lines that are like this, but I feel like I'm going to make it worse if I do it like. Hold on. Let me try.",
    "excerpt": "- All right. And then the eyes. - Let me cook. Let me cook. - This is too much. This is too much detail. - It's a little uneven. I'm going t",
    "wordCount": 88
  },
  {
    "id": "2026-2026-03-26-13",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-26",
    "title": "2026",
    "body": "- Nah, I don't think I like this. Actually, I changed my mind.\n- I wish I could match the hair specifically.\n- Where would it be? This is so useful. Wonder which one it was in the set. I don't see it.\n- He's evil. I think he is kind of evil. I'm pretty sure.\n- Okay. Yeah. Let's go. Like, is he chill? I think\n- I'm scared. Why? Why does that sound so?\n- What is this supposed to be? Is this (truncated)",
    "excerpt": "- Nah, I don't think I like this. Actually, I changed my mind. - I wish I could match the hair specifically. - Where would it be? This is so",
    "wordCount": 86
  },
  {
    "id": "2026-2026-03-31-14",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-03-31",
    "title": "2026",
    "body": "- Hold on. I think I'm going to adjust some stuff. I don't know. I'm indecisive, you know.\n- No, no, no. That's dead. No. Maybe like this.\n- What is this supposed to be? Is this like circles? Kind of like you guys? I can't tell anymore. I'm like nose blind.\n- That's true. Yeah, that's true. Okay, I'm just going to go with this one.",
    "excerpt": "- Hold on. I think I'm going to adjust some stuff. I don't know. I'm indecisive, you know. - No, no, no. That's dead. No. Maybe like this. -",
    "wordCount": 67
  },
  {
    "id": "2026-2026-04-05-15",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-05",
    "title": "2026",
    "body": "- You're not making any sense.\n- It's way too lewd.\n- You gotta think about your timing.\n- I bet the real thing is gonna be really stimulating.",
    "excerpt": "- You're not making any sense. - It's way too lewd. - You gotta think about your timing. - I bet the real thing is gonna be really stimulati",
    "wordCount": 29
  },
  {
    "id": "2026-2026-04-05-16",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-05",
    "title": "2026",
    "body": "- I'm all alone, but it's different somehow from when I'm alone looking for her with no leads.",
    "excerpt": "- I'm all alone, but it's different somehow from when I'm alone looking for her with no leads.",
    "wordCount": 18
  },
  {
    "id": "2026-2026-04-06-17",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-06",
    "title": "2026",
    "body": "- I'm nervous for some reason.\n- Oh my God, Nazuna, you made me do it!\n- Don't say embarrassing crap like that!\n- And at school too, talk about indecent behavior.\n- I guess that means she's never been intimate with a human being.\n- Maybe it will help us get a little bit closer on the wristwatch transceiver...\n\n\n- I thought we could start by being friends.\n- You don't even have any other friends.\n- I kept meaning to ask,\n- What's with the face?\n- From what point do you know that you're friends with someone?\n- I'm making this too complicated, aren't I?\n- Does that mean at one point you became a lot more outgoing around sixth grade?\n- Did I hand it to you in person?\n\n\n- But anyway, I'm glad you're okay.\n- Everyone else only sees you the way you are now.\n- You used to be pretty gloomy, [Akira] You were very standoffish, and showed me by giving me a token of how you felt.\n- You really get a kick out of teasing me, don't you?!\n- I've gotta take care of some things.\n- It's become my routine to meet with Akira though it's not like we really communicate that much.\n- I mean, didn't she used to be more talkative and outgoing?",
    "excerpt": "- I'm nervous for some reason. - Oh my God, Nazuna, you made me do it! - Don't say embarrassing crap like that! - And at school too, talk ab",
    "wordCount": 225
  },
  {
    "id": "2026-2026-04-06-18",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-06",
    "title": "2026",
    "body": "- I feel like she's a lot quieter now.\n- Is this like, you know, if I'm wrong, that's totally fine and all.\n- I see how it is.\n- I was wondering what you were doing behind my back.\n- Is she pissed? She's pissed.\n- What'cha doin' playing hanky panky in a place like this, you naughty boy?",
    "excerpt": "- I feel like she's a lot quieter now. - Is this like, you know, if I'm wrong, that's totally fine and all. - I see how it is. - I was wonde",
    "wordCount": 60
  },
  {
    "id": "2026-2026-04-06-19",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-06",
    "title": "2026",
    "body": "- What else would two kids be doing this late other than hanky panky.\n- Yamori, hold on, do you know this person?\n- My relationship with him is purely physical.\n- So you can relax, missy.\n- No, it's not what you think!\n- Huh? What do you mean by together?\n- Like I said, it's purely physical.\n- Will you stop it?!\n- I'm nervous for some reason.\n- Oh my God, Nazuna, you made me do it!\n- Don't say embarrassing crap like that!\n- And at school too, talk about indecent behavior.\n- I guess that means she's never been intimate with a human being.\n- Maybe it will help us get a little bit closer on the wristwatch transceiver.\n- I thought we could start by being friends.\n- You don't even have any other friends.\n- I kept meaning to ask.\n- What's with the face?\n- From what point do you know that you're friends with someone?\n- I'm making this too complicated, aren't I?\n- Does that mean at one point you became a lot more outgoing around sixth grade?\n- Did I hand it to you in person?\n- But anyway, I'm glad you're okay.\n- Everyone else only sees you the way you are now.\n- You used to be pretty gloomy. You were very standoffish, and showed me by giving me a token of how you felt.\n- You really get a kick out of teasing me, don't you?!\n- I've gotta take care of some things.\n- It's become my routine to meet with Akira though it's not like we really communicate that much.\n- I mean, didn't she used to be more talkative and outgoing?\n- I feel like she's a lot quieter now.\n- Is this like, you know, if I'm wrong, that's totally fine and all.\n- I see how it is.\n- I was wondering what you were doing behind my back.\n- Is she pissed? She's pissed.\n- What'cha doin' playing hanky panky in a place like this, you naughty boy?",
    "excerpt": "- What else would two kids be doing this late other than hanky panky. - Yamori, hold on, do you know this person? - My relationship with him",
    "wordCount": 348
  },
  {
    "id": "2026-2026-04-06-20",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-06",
    "title": "2026",
    "body": "- She's blushing.\n- Enough of that!\n- Why is your face turning all red?\n- Shut it, mind your business, kid!\n- Come on, do we really have to do this?\n- Let me show you something.\n- You better not look away.\n- Huh? You're not being serious! Not here!\n- (Ko whimpers)",
    "excerpt": "- She's blushing. - Enough of that! - Why is your face turning all red? - Shut it, mind your business, kid! - Come on, do we really have to ",
    "wordCount": 55
  },
  {
    "id": "2026-2026-04-06-21",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-06",
    "title": "2026",
    "body": "- Haven't you figured it out?\n- Uh, I'll have a coffee too, thanks.\n- I'll bring that right out.\n- Oh, come on, if you're underage.\n- You're not allowed to drink alcohol.\n- Yamori, I've gotta ask you again, what's with this person?\n- Excuse me! Another beer over here!",
    "excerpt": "- Haven't you figured it out? - Uh, I'll have a coffee too, thanks. - I'll bring that right out. - Oh, come on, if you're underage. - You're",
    "wordCount": 52
  },
  {
    "id": "2026-2026-04-08-22",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-08",
    "title": "2026",
    "body": "- Is this a usual thing?\n- Does it have anything to do with you not coming to school?",
    "excerpt": "- Is this a usual thing? - Does it have anything to do with you not coming to school?",
    "wordCount": 19
  },
  {
    "id": "2026-2026-04-08-23",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-08",
    "title": "2026",
    "body": "- I thought you might not want to talk about it, so I made a point of not asking, but why did you decide to stop showing?\n- As if he needs it anyway.\n- Will the monster please stay quiet for a bit?\n- Hey, boy, this girl's really got some nerve.\n- I thought that I... I was doing fine at school, but then, I don't know, I just couldn't take it anymore.\n- I'm still a vampire whether you like it or not.",
    "excerpt": "- I thought you might not want to talk about it, so I made a point of not asking, but why did you decide to stop showing? - As if he needs i",
    "wordCount": 86
  },
  {
    "id": "2026-2026-04-08-24",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-08",
    "title": "2026",
    "body": "- What have you been doing all this time?\n- Didn't you think to contact him, maybe?\n- I'm not gonna lose sight of you!\n- I totally lost sight of her.\n- Wait, is this our first fight?\n- Angry and ticked off are different?",
    "excerpt": "- What have you been doing all this time? - Didn't you think to contact him, maybe? - I'm not gonna lose sight of you! - I totally lost sigh",
    "wordCount": 46
  },
  {
    "id": "2026-2026-04-10-25",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-10",
    "title": "2026",
    "body": "- Nobody home.\n- Can or the darkness will consume you. I will consume you.\n- But listen, I haven't been sleeping much lately.\n\n\n- What have you been doing?\n- She's usually impossible to locate.\n- Good for them, am I right?\n- M-my heart's pounding really fast.\n- I've achieved my goal of falling in love with a vampire?\n- Something's off.\n- You're firm, huh?\n- Why would I joke about this?\n- I am firm in this belief!\n\n\n- So, what you're saying is, you're like,\n- Obviously, you're not really in love.\n- That's just lust, boy.\n- It's not healthy to think of romantic love and lust as being the same thing.\n- But, however, in this case, that's probably what it is.\n- that feeling I got was arousal?!\n- (Nazuna laughs) That's what it sounds like!\n- What a coincidence.\n\n\n- It was my first, too.\n- Are you sure you should be up this late?\n- But, doesn't the same go for you?\n- Just something to consider.\n- Hmm. Shouldn't that apply to you, too?\n- Suck it, boy!\n- Uh, that's a hard pass.\n- No. It's the kiss I don't want.",
    "excerpt": "- Nobody home. - Can or the darkness will consume you. I will consume you. - But listen, I haven't been sleeping much lately. - What have yo",
    "wordCount": 203
  },
  {
    "id": "2026-2026-04-10-26",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-10",
    "title": "2026",
    "body": "- But, you know, with an obscene monster like her, with a bunch of loudmouth people.\n- [Akira] I'm not that into party games myself.\n- Wait, that's not the point!\n- Right? They all like the protagonist way too much.\n- What's the matter with you?!\n- Your tone's so serious.\n- About a dating sim.\n- [Nazuna] Plus, her tits are freaking huge!\n- Her tits are super huge too.\n\n\n- So, girls you don't have to talk to with large bosoms.\n- You don't have to try to sound so erotic.\n- You like girls that have massive-sized melons?\n- [Akira] I'm a little relieved to know Yamori hasn't changed that much in respect to girls. But it's actually pretty wholesome, I guess.\n- By the way, it's getting close to four o'clock.\n- We don't do anything inappropriate!\n- Nazuna-chan, that's not what you said before!\n- And you say that after you lie down?",
    "excerpt": "- But, you know, with an obscene monster like her, with a bunch of loudmouth people. - [Akira] I'm not that into party games myself. - Wait,",
    "wordCount": 159
  },
  {
    "id": "2026-2026-04-10-27",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-10",
    "title": "2026",
    "body": "- I can't do it! This is way too weird for me!\n- The gates will open in about two hours anyway.\n- Why don't you wait until the rain stops?\n- Do that somewhere else!\n- Having a guilty pleasure is great for spicing things up.\n- What's the deal?\n- It's supply and demand.\n- Right. Is that so?\n- Thanks so much for sugarcoating that comment.\n- You never liked talking about yourself.",
    "excerpt": "- I can't do it! This is way too weird for me! - The gates will open in about two hours anyway. - Why don't you wait until the rain stops? -",
    "wordCount": 76
  },
  {
    "id": "2026-2026-04-10-28",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-10",
    "title": "2026",
    "body": "- Or even what you wanted to be when you got older.\n- What an unimaginative kid.\n- But that's an issue you guys can't avoid.\n- I'm really leaving once the rain lets up.\n- Listen, chill. Don't be such a square.\n- I kind of dragged you into this one.\n- I don't mind.\n- If you don't release the tension in your shoulders.\n- But I'm still gonna try to get you.\n\n\n- To come back to school.\n- I still think it can't hurt to study.\n- I always fall asleep so early.\n- I hope he comes someday, to school.\n- Is it all right if I just leave you here?\n- I'm so close.\n- Huh, that thing I ordered for delivery should be coming soon.\n- I'll destroy Ko next time I play to feel better.\n- I'd feel bad if they kept trying to deliver it to me.\n\n\n- I like how it's nice and dry when I wake up when I wash my clothes then hang them up.\n- Laundry?\n- Vampires have a lot to think about too.\n- [Nazuna] Steam irons again today? That's no fun.\n- Nighttime is inherently fun just for what it is.\n- You doing okay, kitty?\n- Oh, you're such a little cutie pie!\n- Look at your beans!\n- Hmm? Oh gross, stray cat stink.",
    "excerpt": "- Or even what you wanted to be when you got older. - What an unimaginative kid. - But that's an issue you guys can't avoid. - I'm really le",
    "wordCount": 232
  },
  {
    "id": "2026-2026-04-10-29",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-10",
    "title": "2026",
    "body": "- That's stinch is potent!\n- Oh, hello there.\n- Yo, what's up?\n- Can I get one bathing kit?\n- Sure thing.\n- Yeah, kinda.\n- I'm counting on ya.",
    "excerpt": "- That's stinch is potent! - Oh, hello there. - Yo, what's up? - Can I get one bathing kit? - Sure thing. - Yeah, kinda. - I'm counting on y",
    "wordCount": 31
  },
  {
    "id": "2026-2026-04-11-30",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Ko Yamori, age 14, eighth grade.\n- I was getting by just fine.\n- Suddenly I just couldn't be bothered anymore.\n- The most pressing issue is that I can't sleep.\n- Says online that I should talk to a family member.",
    "excerpt": "- Ko Yamori, age 14, eighth grade. - I was getting by just fine. - Suddenly I just couldn't be bothered anymore. - The most pressing issue i",
    "wordCount": 43
  },
  {
    "id": "2026-2026-04-11-31",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Do they know I snuck out?\n- I never knew vending machines were this bright at night.\n- Oh, you're buying booze?\n- How nice.\n- You sure don't look like you're over 20 years old.\n- But more importantly, I...\n- Just an honest mistake, okay? Well, gotta go!\n- You think that's gonna fool me, boy?\n- This isn't what you think, really.\n- It all boils down to one inevitable conclusion,",
    "excerpt": "- Do they know I snuck out? - I never knew vending machines were this bright at night. - Oh, you're buying booze? - How nice. - You sure don",
    "wordCount": 75
  },
  {
    "id": "2026-2026-04-11-32",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- See how satisfied they are?\n- Fast asleep with no discontent whatsoever.\n- [Ko] Aren't they just totally wasted?\n- if you don't release your inhibitions, sweet boy.\n- Hey, where are you going?\n- Release inhibitions?\n- I-I wouldn't have this problem if I could do that.\n- This always happens.",
    "excerpt": "- See how satisfied they are? - Fast asleep with no discontent whatsoever. - [Ko] Aren't they just totally wasted? - if you don't release yo",
    "wordCount": 53
  },
  {
    "id": "2026-2026-04-11-33",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Hey, guys, don't let that booze consume you.\n- Tell me, how does it feel to let go of yourself a bit?\n- This doesn't look like a trashy place, at least.\n- Gotta go, you're freaking me out! Goodbye!\n- Hey, not so fast, boy.\n- Anyone can tell she's a psycho, but why is this so relaxing?\n- I'll pretend to be asleep for a while and then go home.\n- You up?\n- Boy, are you actually asleep or just faking it?\n- Thank goodness you really fell asleep.",
    "excerpt": "- Hey, guys, don't let that booze consume you. - Tell me, how does it feel to let go of yourself a bit? - This doesn't look like a trashy pl",
    "wordCount": 93
  },
  {
    "id": "2026-2026-04-11-34",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- I can't wait any longer.\n- Well then, it's feeding time.\n- A mosquito...\n- It was worth a try.\n- So would you happen to be a vampire of some sort?\n- So then why is it that I'm not a vampire?\n- That would suck and freak me out.\n- Wouldn't it suck if you got a new family member, hear there's vampires who create loads of offspring, but I'm not interested in that kind of thing.",
    "excerpt": "- I can't wait any longer. - Well then, it's feeding time. - A mosquito... - It was worth a try. - So would you happen to be a vampire of so",
    "wordCount": 80
  },
  {
    "id": "2026-2026-04-11-35",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- You didn't even answer my question.\n- Loud? I'm not being loud.\n- You see, I don't wanna go around telling everybody this news...\n- Well, uh, anyway, basically,\n- Just like how a child results\n- Oh, why are you being gross all of a sudden?\n- Humans can only create offspring through intense copulation.\n- And then who all is hooking up.\n- And who's making out.",
    "excerpt": "- You didn't even answer my question. - Loud? I'm not being loud. - You see, I don't wanna go around telling everybody this news... - Well, ",
    "wordCount": 70
  },
  {
    "id": "2026-2026-04-11-36",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Why do you look freaked out?\n- I really don't understand that kind of thing.\n- Don't you have a crush on anyone at school?\n- Why can't you shut up?\n- Okay, I'm off.\n- Oh, screw this.\n- Wow, middle school can be tough, huh?\n- And started fooling around at night.\n- Tell me, boy, how does your first night out feel?\n- What do you think now that you've taken a step (truncated)",
    "excerpt": "- Why do you look freaked out? - I really don't understand that kind of thing. - Don't you have a crush on anyone at school? - Why can't you",
    "wordCount": 78
  },
  {
    "id": "2026-2026-04-11-37",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Outside your little comfort zone?\n- This place is the furthest you can hope to get away.\n- It would be a waste if you didn't keep this kind of thing up.\n- It's not a bad way to live.\n- So yeah, do me a favor, Miss Vampire!\n- I have to ask of you.\n- I'd never take that leap.",
    "excerpt": "- Outside your little comfort zone? - This place is the furthest you can hope to get away. - It would be a waste if you didn't keep this kin",
    "wordCount": 63
  },
  {
    "id": "2026-2026-04-11-38",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- and spend day after day in boredom.\n- It's the first time I've wanted something.\n- I won't deny this feeling.\n- (sighs) You're being ridiculous.\n- It's my policy not to create offspring.\n- If you fall for me, that's your deal.\n- that's because the blood is infused with night.\n- What? If you think about the distance to the moon, the difference between the ground and the roof isn't that much.",
    "excerpt": "- and spend day after day in boredom. - It's the first time I've wanted something. - I won't deny this feeling. - (sighs) You're being ridic",
    "wordCount": 75
  },
  {
    "id": "2026-2026-04-11-39",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- That's why I wanna infuse more night in you, boy.\n- Uh, you mean I need to stay up late?\n- Well, I plan to do that anyway.\n- That too, of course.\n- I'm gonna die! No, you won't.\n- The night is for fooling around.\n- Hang on tight, it's go time.\n- It's another beautiful night out.\n- Huh? You don't know? I got you.\n- Well, it's not like I really care either way.",
    "excerpt": "- That's why I wanna infuse more night in you, boy. - Uh, you mean I need to stay up late? - Well, I plan to do that anyway. - That too, of ",
    "wordCount": 79
  },
  {
    "id": "2026-2026-04-11-40",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-11",
    "title": "2026",
    "body": "- Have you forgotten what you came here to do with me?",
    "excerpt": "- Have you forgotten what you came here to do with me?",
    "wordCount": 12
  },
  {
    "id": "2026-2026-04-12-41",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-12",
    "title": "2026",
    "body": "- Yeah. Keep your hands off our Honmoon.\n- That choice belongs to you.\n- Your loss.\n- We just wanted to stop by and congratulate our hoobaes on their debut and--\n- Me too. I thought I wanted couch, but I think couch can wait.",
    "excerpt": "- Yeah. Keep your hands off our Honmoon. - That choice belongs to you. - Your loss. - We just wanted to stop by and congratulate our hoobaes",
    "wordCount": 46
  },
  {
    "id": "2026-2026-04-13-42",
    "fileName": "2026.md",
    "relativePath": "2026.md",
    "date": "2026-04-13",
    "title": "2026",
    "body": "- Oh okay um we're going to leave it like this okay.\n- Is a newer game so that's understandable that it would be winning.\n- That I'm not that tall I think it's just cuz my legs look long.\n- Now you should be getting the. (truncated)",
    "excerpt": "- Oh okay um we're going to leave it like this okay. - Is a newer game so that's understandable that it would be winning. - That I'm not tha",
    "wordCount": 48
  }
] as const;
