// This file is generated by npm run import:cards
export const importedNoteSections = [
  {
    "id": "demo-2026-04-17-1",
    "fileName": "demo.md",
    "relativePath": "demo.md",
    "date": "2026-04-17",
    "title": "Travel Phrases",
    "body": "- board the train\n- miss the stop\n- keep an eye on your bag\n\nSay:\n\"I nearly missed my stop because I was reading.\"\n\nTry one new sentence aloud before recording this review.",
    "excerpt": "- board the train - miss the stop - keep an eye on your bag Say: \"I nearly missed my stop because I was reading.\" Try one new sentence aloud",
    "wordCount": 34
  },
  {
    "id": "demo-2026-04-18-2",
    "fileName": "demo.md",
    "relativePath": "demo.md",
    "date": "2026-04-18",
    "title": "Work Vocabulary",
    "body": "- follow up\n- deadline\n- rough draft\n\nSay:\n\"I will follow up with a rough draft before Friday.\"\n\nNotice how \"follow up\" changes between a verb and a noun.",
    "excerpt": "- follow up - deadline - rough draft Say: \"I will follow up with a rough draft before Friday.\" Notice how \"follow up\" changes between a verb",
    "wordCount": 30
  },
  {
    "id": "demo-2026-04-19-3",
    "fileName": "demo.md",
    "relativePath": "demo.md",
    "date": "2026-04-19",
    "title": "Small Talk",
    "body": "- How has your week been?\n- That sounds exciting.\n- I have been meaning to try that.\n\nUse one question and one follow-up answer in the same conversation today.",
    "excerpt": "- How has your week been? - That sounds exciting. - I have been meaning to try that. Use one question and one follow-up answer in the same c",
    "wordCount": 30
  }
] as const;
